spring.application.name=Placement_Drive_Management

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
spring.main.lazy-initialization=true
spring.jpa.open-in-view=false
spring.profiles.active = prod
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5

# Validate connection before using it
spring.datasource.hikari.connection-test-query=SELECT 1
