spring.application.name=Placement_Drive_Management
spring.profiles.active=prod
spring.main.lazy-initialization=true
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always