server.port=${PORT:10000}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
cloudinary.cloud_name=dgdjc9gdh
cloudinary.api_key=325442679113853
cloudinary.api_secret=_d3VUQwXX280i3QnDYsLmYnkmFQ
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url = jdbc:postgresql://localhost:5432/pdmsDB
spring.datasource.username = postgres
spring.datasource.password = postgresql123
app.jwt.secret=PLACEMENT_DRIVE_MANAGEMENT_SYSTEM_JWT_SECRET_WITH_LONG_TEXT
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000
superadmin.email=superAdmin@anits.edu.in
superadmin.password=superAdmin@123
superadmin.name=ANITS
